In [1]:
# Q1

import pandas as pd

data = {
    "Daily Action": [
        "Instagram Likes",
        "Instagram Comment",
        "Zomato Rating",
        "Flipkart Product Category",
        "Flipkart Order Amount"
    ],
    "Data Type": [
        "Numerical",
        "Categorical",
        "Numerical",
        "Categorical",
        "Numerical"
    ]
}

df = pd.DataFrame(data)
df

                Daily Action    Data Type
0            Instagram Likes    Numerical
1          Instagram Comment  Categorical
2              Zomato Rating    Numerical
3  Flipkart Product Category  Categorical
4      Flipkart Order Amount    Numerical

In [2]:
# Q2

music = ['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop']

print("Data:", music)
print("\nType of Data: Categorical")

print("""
Reason:
The values are music genres.
They are names (labels), not numbers, so this is categorical data.
""")

Data: ['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop']

Type of Data: Categorical

Reason:
The values are music genres.
They are names (labels), not numbers, so this is categorical data.

In [3]:
# Q3

feature = "Instagram Likes"

print("Feature:", feature)

print("""
Statistics can help find the average number of likes on posts.
It can recommend popular posts to users based on engagement.
""")

Feature: Instagram Likes

Statistics can help find the average number of likes on posts.
It can recommend popular posts to users based on engagement.

In [4]:
# Q4

terms = {
    "Mean": "Average songs listened per day. Example: 40 songs/day.",
    "Median": "Middle value of daily listening time. Example: 60 minutes.",
    "Mode": "Most frequently played genre. Example: Pop."
}

df = pd.DataFrame(terms.items(), columns=["Statistical Term", "Example"])
df

  Statistical Term                                            Example
0             Mean  Average songs listened per day. Example: 40 so...
1           Median  Middle value of daily listening time. Example:...
2             Mode        Most frequently played genre. Example: Pop.